version: '3'
services:
    rtorrent:
        image: dtorrent:latest
        restart: always
        volumes:
            - ./data/downloaded:/var/rtorrent/downloaded
            - ./data/torrent:/var/rtorrent/torrents
            - ./data/logs:/var/rtorrent/logs
            - ./clients/rtorrent:/home/toto
        tty: true
    nginx:
        image: nginx:1.13
        ports:
            - 8089:8089
        links:
            - rtorrent
        volumes:
          - ./docker/nginx/conf.d:/etc/nginx/conf.d