#!/bin/sh -e
#
### BEGIN INIT INFO
# Provides: rtorrentd
# Required-Start: $network $syslog
# Required-Stop: $network
# Default-Start: 2 3 5
# Default-Stop: 0 1 6
# Description: Démarrer/arrêter rtorrent sous forme de daemon.
### END INIT INFO
user=root
NAME=rtorrentd
SCRIPTNAME=/etc/init.d/$NAME
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# path du fichier temporaire
TMP=/tmp/rtorrent.dtach
# user qui lance le torrent

# chemin vers fichier conf
CONF=/root/.rtorrent.rc

start() {
        echo -n $"Starting $NAME: "
        su -l ${user} -c "dtach -n $TMP rtorrent -n -o import=$CONF"
        chmod 666 /tmp/rtorrent.dtach
        echo "started"
}

stop() {
        echo -n $"Stopping $NAME: "
        killall -r "rtorrent"
        echo "stopped"
}

restart() {

        if [ "$(ps aux | grep -e 'rtorrent' -c)" != 0  ]; then
        {
                stop
                sleep 5
        }
        fi
        start
}


case $1 in
        start)
               start
        ;;
        stop)
                stop
        ;;
        restart)
                restart
        ;;
        *)
                echo "Usage:  {start|stop|restart}" >&2
                exit 2
        ;;
esac